primerExamenProgramacionIII/Controllers/EstudiantesController.cs
using Microsoft.AspNetCore.Http;
using primerExamenProgramacionIII.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace primerExamenProgramacionIII.Controllers
{
    public class EstudiantesController : Controller
    {
        // GET: EstudiantesController
        public ActionResult Index()
        {
            // Se le envia al Index la informacion de las lista para mostrar a los Estudiantes
            ListaEstudiantes le = ListaEstudiantes.Lalista;
            return View(le.Estudiante);
        }

        [RequireHttps]
        public IActionResult buscarEstudiantes(string texto)
        {
            // Se crea una funcionalidad para buscar a los estudiantes y se compara con el nombre

            ListaEstudiantes lp = ListaEstudiantes.Lalista;
            var estudiante = lp.Estudiante.Where(x => x.Nombre.Contains(texto));

            if (estudiante == null)
            {
                return NotFound();
            }
            else
            {
                return View(estudiante);
            }

        }

        // GET: EstudiantesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EstudiantesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EstudiantesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EstudiantesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EstudiantesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EstudiantesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EstudiantesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

primerExamenProgramacionIII/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using primerExamenProgramacionIII.Models;
using System.Diagnostics;

namespace primerExamenProgramacionIII.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

primerExamenProgramacionIII/Controllers/ProfesoresController.cs
using Microsoft.AspNetCore.Http;
using primerExamenProgramacionIII.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace primerExamenProgramacionIII.Controllers
{
    public class ProfesoresController : Controller
    {
        // GET: ProfesoresController
        public ActionResult Index()
        {
            // Se le envia al Index la informacion de las lista para mostrar a los Profesores
            ListaProfesores lp = ListaProfesores.Lalista;
            return View(lp.Profesor);

        }

        [RequireHttps]
        public IActionResult buscarProfesores(string texto)
        {
            // Se crea una funcionalidad para buscar a los profesores y se compara con el nombre
            ListaProfesores lp = ListaProfesores.Lalista;
            var profesores = lp.Profesor.Where(x => x.Nombre.Contains(texto));

            if(profesores == null)
            {
                return NotFound();
            }
            else
            {
                return View(profesores);
            }
            
        }


        // GET: ProfesoresController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProfesoresController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProfesoresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfesoresController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProfesoresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfesoresController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProfesoresController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

primerExamenProgramacionIII/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="hero text-center">
    <h1>Busqueda de Estudiantes y Profesores</h1>
    <p>Jossue D. Rodriguez Mora</p>
    <a href="#personas" class="btn btn-dark">Buscar</a>
</div>

<div class="container m-a " id="personas">

   <div class="row">
      <div class="col">
          <!--Card 1 Profesor-->
        <div class="card">
          <img src="https://images.pexels.com/photos/3771074/pexels-photo-3771074.jpeg" class="card-img-top" alt="..." height="200">
          <div class="card-body">
            <h5 class="card-title">Profesores</h5>
            <p class="card-text">Por medio de esta funcion se puden ver los profesores y realizar una busqueda por nombre si desea encontrar uno en especifico</p>
            <a asp-action="index" asp-controller="Profesores" class="btn btn-dark">Buscar Profesor</a>
          </div>
        </div>
      </div>

    <div class="col">
         <!--Card 2 Estudiantes-->
         <div class="card">
          <img src="https://images.pexels.com/photos/1454360/pexels-photo-1454360.jpeg" class="card-img-top" alt="..."  height="200">
          <div class="card-body">
            <h5 class="card-title">Estudiantes</h5>
            <p class="card-text">Por medio de esta funcion se puden ver los estudiantes y realizar una busqueda por nombre si desea encontrar uno en especifico</p>
            <a asp-action="index" asp-controller="Estudiantes" class="btn btn-dark">Buscar Estudiante</a>
          </div>
        </div>
      </div>
    </div>
</div>